networks:
  seckill-network:
    driver: bridge

volumes:
  prometheus_data: {}
services:
  mysql:
    image: mysql:5.7
    container_name: seckill-mysql
    volumes:
    - ./data/db_data:/var/lib/mysql
    - ./config/mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill
      MYSQL_USER: binghe
      MYSQL_PASSWORD: binghe
    ports:
    - 13306:3306
    networks:
    - seckill-network

  redis:
    container_name: seckill-redis
    image: redis:7.0
    ports:
    - 16379:6379
    networks:
    - seckill-network
  redis-commander:
    container_name: seckill-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:seckill-redis:6379
    ports:
    - 18082:8081
    networks:
    - seckill-network
  rmqnamesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: seckill-rmqnamesrv
    ports:
    - 19876:9876
    volumes:
    - ./data/rocketmq/logs:/home/rocketmq/logs
    - ./data/rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
    - seckill-network
  rmqbroker:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: seckill-rmqbroker
    ports:
    - 10909:10909
    - 10911:10911
    - 10912:10912
    volumes:
    - ./data/rocketmq/logs:/home/rocketmq/logs
    - ./data/rocketmq/store:/home/rocketmq/store
    - ./config/rocketmq/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -n seckill-rmqnamesrv:9876 -c ../conf/broker.conf
    depends_on:
    - rmqnamesrv
    environment:
    - JAVA_HOME=/usr/lib/jvm/jre
    networks:
    - seckill-network

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: seckill-elasticsearch
    volumes:
    - ./config/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
    - "19200:9200"
    - "19300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
    - seckill-network

  logstash:
    image: logstash:7.14.2
    container_name: seckill-logstash
    volumes:
    - ./config/elk/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./config/elk/pipeline:/usr/share/logstash/pipeline
    ports:
    - "15044:5044"
    - "15000:5000/tcp"
    - "15000:5000/udp"
    - "19600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - seckill-network
    depends_on:
    - elasticsearch

  kibana:
    image: kibana:7.14.2
    container_name: seckill-kibana
    volumes:
    - ./config/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - "15601:5601"
    networks:
    - seckill-network
    depends_on:
    - elasticsearch

  sentinel:
    image: bladex/sentinel-dashboard
    container_name: seckill-sentinel
    ports:
      - 18858:8858
    networks:
      - seckill-network

  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: seckill-nacos
    env_file:
    - ./config/nacos/nacos-standlone-mysql.env
    volumes:
    - ./data/nacos_logs/:/home/nacos/logs
    - ./config/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - 18848:8848
    - 19848:9848
    - 19555:9555
    depends_on:
    - mysql
    restart: on-failure
    networks:
    - seckill-network
